# This workflow will install dependencies (including nox), using those to lint and run tests

name: Nox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  run_nox:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox
    - name: Lint
      run: |
        nox -s flake
    - name: Typing
      run: |
        nox -s mypy
    - name: Docs linting
      run: |
        nox -s lint_docs
    - name: Test Suite
      run: |
        nox -t test